[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.isort]
multi_line_output = 10
line_length = 119
skip_gitignore = true
use_parentheses = true

[tool.black]
line-length = 119

[tool.mypy]
ignore_missing_imports = true
install_types = true
pretty = true
non_interactive = true
