[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 79

[tool.isort]
line_length = 79
profile = "black"
skip_gitignore = true

[tool.mypy]
ignore_missing_imports = true
install_types = true
pretty = true
non_interactive = true
