[project]
name = "fl4health"
version = "0.0.1"
authors = [
  { name="AI Engineering", email="ai_engineering@vectorinstitute.ai" },
]
description = "Federated Learning for Health"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 119

[tool.isort]
line_length = 119
profile = "black"
skip_gitignore = true
