# Parameters that describe server
n_server_rounds: 50 # The number of rounds to run FL

# Parameters that describe clients
n_clients: 2 # The number of clients in the FL experiment
local_epochs: 4 # The number of epochs to complete for client
batch_size: 64 # The batch size for client training


reporting_config:
  enabled: False
  project_name: FL4Health # Name of the project under which everything should be logged
  run_name: "FedAvg Server" # Name of the run on the server-side, each client will also have it's own run name
  group_name: "FedAvg Experiment" # Group under which each of the FL run logging will be stored
  entity: "your_entity_here" # WandB user name
  notes: "Testing WB reporting"
  tags: ["Test", "FedAvg"]
