
version: '3'
services:

    fl_server:
        build: fl_server
        container_name: fl_server
        ports:
        - "5000:8080"
        environment:
            SERVER_INTERNAL_HOST: "0.0.0.0"
            SERVER_INTERNAL_PORT: "8080"
            NUM_CLIENTS: 2
            NUM_ROUNDS: 10

    fl_client_1:
        build: fl_client
        container_name: fl_client_1
        depends_on:
        - fl_server
        environment:
            FLOWER_SERVER_URL: "fl_server:8080"
            FLOWER_CLIENT_NUMBER: "1"

    fl_client_2:
        build: fl_client
        container_name: fl_client_2
        depends_on:
        - fl_server
        environment:
            FLOWER_SERVER_URL: "fl_server:8080"
            FLOWER_CLIENT_NUMBER: "2"
