# Parameters that describe server
n_server_rounds: 10 # The number of rounds to run FL

# Parameters that describe clients
n_clients: 2 # The number of clients in the FL experiment
local_epochs: 10 # The number of epochs to complete for client
batch_size: 64 # The batch size for client training
# id_column: "ID"
# target_column: "outcome"
format_specified: False
