# You should set these yourself

# General settings for basic client
#==================================
# Required settings:
n_clients: 1
n_server_rounds: 1
server_address: '0.0.0.0:8080'
# Use either local epochs or steps, not both
local_epochs: 3
# local_steps: 50

# Optional Settings:
#starting_checkpoint: /home/shawn/Code/nnunet_storage/nnUNet_results/Dataset004_Hippocampus/nnUNetTrainer_1epoch__nnUNetPlans__2d/fold_0/checkpoint_best.pth

# Settings specific to nnunet client
#==================================
# Required settings:
nnunet_config: 2d
fold: 0

# Optional settings
#nnunet_plans: /home/shawn/Code/nnunet_storage/nnUNet_preprocessed/Dataset004_Hippocampus/nnUNetPlans.json







