# Parameters that describe server
n_server_rounds: 10 # The number of rounds to run FL

adaptive_proximal_weight: False # Whether to use adaptive proximal weight or not
proximal_weight : 0.1 # Initial proximal weight
proximal_weight_delta : 0.1 # The amount by which to increase or decrease the proximal weight, if adaptive_proximal_weight is True
proximal_weight_patience : 5 # The number of rounds to wait before increasing or decreasing the proximal weight, if adaptive_proximal_weight is True


# Parameters that describe clients
n_clients: 3 # The number of clients in the FL experiment
local_epochs: 1 # The number of epochs to complete for client (NOT USED FOR FLAMBY)
batch_size: 64 # The batch size for client training (NOT USED FOR FLAMBY)
local_steps: 100 # The number of local training steps to perform.
