# Parameters that describe server
n_server_rounds: 4 # The number of rounds to run FL

# Parameters that describe clients
n_clients: 5 # The number of clients in the FL experiment
local_epochs: 1 # The number of epochs to complete for client
batch_size: 4 # The batch size for client training

num_classes: 4 # number of classes in the classification task

sequence_length: 256 # the length of tokenized sequences

normalize: False
filter_by_percentage: True

sample_percentage: 0.75
beta: 0.5
