# only has to pass for python 3.9
name: Static code checks

on:
  push:
    branches:
      main
  pull_request:
    branches:
      main

jobs:
  run-code-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check disk space
        run: df . -h
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
          cache: 'pip'
      - name: precommit checks
        run: |
          pip install --upgrade pip
          pip install $(grep -v '^portalocker\|^torchdata\|^torchtext'\|^torcheval requirements.txt | grep .)
          pre-commit run --all-files
      - name: Check disk space
        run: df . -h
