# only has to pass for python 3.9
name: PyTest Unit Tests

on:
  push:
    branches:
      main
  pull_request:
    branches:
      main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check disk space
        run: df . -h
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
          cache: 'pip'
      # Display the Python version being used
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install Requirements
        run: |
          pip install --upgrade pip
          pip install $(grep -v '^portalocker\|^torchdata\|^torchtext\|^torcheval' requirements.txt)
          pip uninstall portalocker
      - name: Run Tests
        run: pytest tests/*
      - name: Check disk space
        run: df . -h
